const SYMBOL_MAP: Record<string, string> = {
  clearsky_day: '01d',
  clearsky_night: '01n',
  clearsky_polartwilight: '01m',
  fair_day: '02d',
  fair_night: '02n',
  fair_polartwilight: '02m',
  partlycloudy_day: '03d',
  partlycloudy_night: '03n',
  partlycloudy_polartwilight: '03m',
  cloudy: '04',
  lightrainshowers_day: '40d',
  lightrainshowers_night: '40n',
  lightrainshowers_polartwilight: '40m',
  rainshowers_day: '05d',
  rainshowers_night: '05n',
  rainshowers_polartwilight: '05m',
  heavyrainshowers_day: '41d',
  heavyrainshowers_night: '41n',
  heavyrainshowers_polartwilight: '41m',
  lightrainshowersandthunder_day: '24d',
  lightrainshowersandthunder_night: '24n',
  lightrainshowersandthunder_polartwilight: '24m',
  rainshowersandthunder_day: '06d',
  rainshowersandthunder_night: '06n',
  rainshowersandthunder_polartwilight: '06m',
  heavyrainshowersandthunder_day: '25d',
  heavyrainshowersandthunder_night: '25n',
  heavyrainshowersandthunder_polartwilight: '25m',
  lightsleetshowers_day: '42d',
  lightsleetshowers_night: '42n',
  lightsleetshowers_polartwilight: '42m',
  sleetshowers_day: '07d',
  sleetshowers_night: '07n',
  sleetshowers_polartwilight: '07m',
  heavysleetshowers_day: '43d',
  heavysleetshowers_night: '43n',
  heavysleetshowers_polartwilight: '43m',
  lightsleetshowersandthunder_day: '26d',
  lightsleetshowersandthunder_night: '26n',
  lightsleetshowersandthunder_polartwilight: '26m',
  sleetshowersandthunder_day: '20d',
  sleetshowersandthunder_night: '20n',
  sleetshowersandthunder_polartwilight: '20m',
  heavysleetshowersandthunder_day: '27d',
  heavysleetshowersandthunder_night: '27n',
  heavysleetshowersandthunder_polartwilight: '27m',
  lightsnowshowers_day: '44d',
  lightsnowshowers_night: '44n',
  lightsnowshowers_polartwilight: '44m',
  snowshowers_day: '08d',
  snowshowers_night: '08n',
  snowshowers_polartwilight: '08m',
  heavysnowshowers_day: '45d',
  heavysnowshowers_night: '45n',
  heavysnowshowers_polartwilight: '45m',
  lightsnowshowersandthunder_day: '28d',
  lightsnowshowersandthunder_night: '28n',
  lightsnowshowersandthunder_polartwilight: '28m',
  snowshowersandthunder_day: '21d',
  snowshowersandthunder_night: '21n',
  snowshowersandthunder_polartwilight: '21m',
  heavysnowshowersandthunder_day: '29d',
  heavysnowshowersandthunder_night: '29n',
  heavysnowshowersandthunder_polartwilight: '29m',
  lightrain: '46',
  rain: '09',
  heavyrain: '10',
  lightrainandthunder: '30',
  rainandthunder: '22',
  heavyrainandthunder: '11',
  lightsleet: '47',
  sleet: '12',
  heavysleet: '48',
  lightsleetandthunder: '31',
  sleetandthunder: '23',
  heavysleetandthunder: '32',
  lightsnow: '49',
  snow: '13',
  heavysnow: '50',
  lightsnowandthunder: '33',
  snowandthunder: '14',
  heavysnowandthunder: '34',
  fog: '15',
};

export function symbolCodeToSvg(code: string): string {
  const id = SYMBOL_MAP[code] ?? '04';
  return `/weather-icons/${id}.svg`;
}

const NORSK: Record<string, string> = {
  clearsky_day: 'Klarvær',
  clearsky_night: 'Klarvær',
  clearsky_polartwilight: 'Klarvær',
  fair_day: 'Lettskyet',
  fair_night: 'Lettskyet',
  fair_polartwilight: 'Lettskyet',
  partlycloudy_day: 'Delvis skyet',
  partlycloudy_night: 'Delvis skyet',
  partlycloudy_polartwilight: 'Delvis skyet',
  cloudy: 'Skyet',
  lightrainshowers_day: 'Lette regnbyger',
  lightrainshowers_night: 'Lette regnbyger',
  lightrainshowers_polartwilight: 'Lette regnbyger',
  rainshowers_day: 'Regnbyger',
  rainshowers_night: 'Regnbyger',
  rainshowers_polartwilight: 'Regnbyger',
  heavyrainshowers_day: 'Kraftige regnbyger',
  heavyrainshowers_night: 'Kraftige regnbyger',
  heavyrainshowers_polartwilight: 'Kraftige regnbyger',
  lightrainshowersandthunder_day: 'Lette regnbyger og torden',
  lightrainshowersandthunder_night: 'Lette regnbyger og torden',
  lightrainshowersandthunder_polartwilight: 'Lette regnbyger og torden',
  rainshowersandthunder_day: 'Regnbyger og torden',
  rainshowersandthunder_night: 'Regnbyger og torden',
  rainshowersandthunder_polartwilight: 'Regnbyger og torden',
  heavyrainshowersandthunder_day: 'Kraftige regnbyger og torden',
  heavyrainshowersandthunder_night: 'Kraftige regnbyger og torden',
  heavyrainshowersandthunder_polartwilight: 'Kraftige regnbyger og torden',
  lightsleetshowers_day: 'Lette sluddbyger',
  lightsleetshowers_night: 'Lette sluddbyger',
  lightsleetshowers_polartwilight: 'Lette sluddbyger',
  sleetshowers_day: 'Sluddbyger',
  sleetshowers_night: 'Sluddbyger',
  sleetshowers_polartwilight: 'Sluddbyger',
  heavysleetshowers_day: 'Kraftige sluddbyger',
  heavysleetshowers_night: 'Kraftige sluddbyger',
  heavysleetshowers_polartwilight: 'Kraftige sluddbyger',
  lightsleetshowersandthunder_day: 'Lette sluddbyger og torden',
  lightsleetshowersandthunder_night: 'Lette sluddbyger og torden',
  lightsleetshowersandthunder_polartwilight: 'Lette sluddbyger og torden',
  sleetshowersandthunder_day: 'Sluddbyger og torden',
  sleetshowersandthunder_night: 'Sluddbyger og torden',
  sleetshowersandthunder_polartwilight: 'Sluddbyger og torden',
  heavysleetshowersandthunder_day: 'Kraftige sluddbyger og torden',
  heavysleetshowersandthunder_night: 'Kraftige sluddbyger og torden',
  heavysleetshowersandthunder_polartwilight: 'Kraftige sluddbyger og torden',
  lightsnowshowers_day: 'Lette snøbyger',
  lightsnowshowers_night: 'Lette snøbyger',
  lightsnowshowers_polartwilight: 'Lette snøbyger',
  snowshowers_day: 'Snøbyger',
  snowshowers_night: 'Snøbyger',
  snowshowers_polartwilight: 'Snøbyger',
  heavysnowshowers_day: 'Kraftige snøbyger',
  heavysnowshowers_night: 'Kraftige snøbyger',
  heavysnowshowers_polartwilight: 'Kraftige snøbyger',
  lightsnowshowersandthunder_day: 'Lette snøbyger og torden',
  lightsnowshowersandthunder_night: 'Lette snøbyger og torden',
  lightsnowshowersandthunder_polartwilight: 'Lette snøbyger og torden',
  snowshowersandthunder_day: 'Snøbyger og torden',
  snowshowersandthunder_night: 'Snøbyger og torden',
  snowshowersandthunder_polartwilight: 'Snøbyger og torden',
  heavysnowshowersandthunder_day: 'Kraftige snøbyger og torden',
  heavysnowshowersandthunder_night: 'Kraftige snøbyger og torden',
  heavysnowshowersandthunder_polartwilight: 'Kraftige snøbyger og torden',
  lightrain: 'Lett regn',
  rain: 'Regn',
  heavyrain: 'Kraftig regn',
  lightrainandthunder: 'Lett regn og torden',
  rainandthunder: 'Regn og torden',
  heavyrainandthunder: 'Kraftig regn og torden',
  lightsleet: 'Lett sludd',
  sleet: 'Sludd',
  heavysleet: 'Kraftig sludd',
  lightsleetandthunder: 'Lett sludd og torden',
  sleetandthunder: 'Sludd og torden',
  heavysleetandthunder: 'Kraftig sludd og torden',
  lightsnow: 'Lett snø',
  snow: 'Snø',
  heavysnow: 'Kraftig snø',
  lightsnowandthunder: 'Lett snø og torden',
  snowandthunder: 'Snø og torden',
  heavysnowandthunder: 'Kraftig snø og torden',
  fog: 'Tåke',
};

export function symbolCodeToNorwegian(code: string): string {
  return NORSK[code] ?? 'Skyet';
}
